import { Breadcrumb } from "@/components/Breadcrumb";
import { bySegment, byTeam, campaignConversion, featureRequestCounts } from "@/lib/analytics";
import type { Opp } from "@/lib/types";
import groundTruthJson from "@/fixtures/ground_truth.json";

const opps = groundTruthJson as Opp[];
function FeatureTable({ rows }: { rows: Opp[] }) { const counts = featureRequestCounts(rows); return <div className="space-y-2">{counts.slice(0, 5).map((x) => <div key={x.feature} className="flex justify-between border-b border-border py-2 text-sm"><span>{x.feature}</span><span className="font-semibold">{x.count}</span></div>)}</div>; }

export default function TeamsPage() { const signal = campaignConversion("signal"); return <div><Breadcrumb items={[{ label: "Teams" }]} /><h1 className="text-2xl font-bold">Break-outs by team and segment</h1><p className="mt-2 text-sm text-muted">The same golden data can be split by the operating groups VPs manage. These are read-only rollups from the analytics book.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{byTeam((rows) => ({ features: featureRequestCounts(rows)[0], closed: rows.filter((o) => o.outcome !== "open").length, pipeline: rows.reduce((n, o) => n + o.deal_amount, 0) })).map(({ team, value }) => <section key={team} className="card p-4"><h2 className="font-semibold">{team}</h2><p className="mt-3 text-sm text-muted">Top request</p><p className="text-lg font-semibold">{value.features?.feature ?? "—"}</p><p className="text-xs text-muted">{value.features?.count ?? 0} cited · {value.closed} closed · ${(value.pipeline / 1000000).toFixed(1)}M pipeline</p><div className="mt-4"><FeatureTable rows={opps.filter((o) => o.team === team)} /></div></section>)}</div><section className="mt-8"><h2 className="text-lg font-semibold">Segment conversion context</h2><div className="mt-3 grid gap-3 md:grid-cols-3">{bySegment((rows) => ({ opps: rows.length, signalRate: signal.rate })).map(({ segment, value }) => <div key={segment} className="card p-4"><p className="font-medium">{segment}</p><p className="mt-2 text-2xl font-semibold">{value.opps}</p><p className="text-xs text-muted">opportunities · signal nurture benchmark {value.signalRate}%</p></div>)}</div></section></div>; }

