# -*- coding: utf-8 -*-
"""
Field Intelligence System - Synthetic Data Factory (v2)
=======================================================

NOTE (committed as a methodology artifact):
  The committed fixtures/envelopes.json + ground_truth.json were produced by an
  earlier run plus 2 hand-authored historical "won vs Zendesk" win-wires (Massive
  Dynamic, Prestige Worldwide) so the golden-route pattern fires at 3. To keep the
  calibrated demo stable, fixtures/touches.json is generated by
  scripts/generate-touches.ts BOUND TO those committed accounts (same account_ids
  and trajectories) rather than by re-running this file. This file is the canonical
  methodology: v2 adds a second dial — PROGRESSION ("how far along") from structured
  Outreach/Marketo/call/email touches, kept separate from HEALTH ("how well it's
  going"). Touches are activity, NOT conversations, and never go through extraction.

METHODOLOGY (what you present)
-----------------------------
  1. PLANT THE ANSWER FIRST — decide each account's hidden ground-truth profile.
  2. HIDE IT IN PROSE — front-half MEDDPICC on calls, back-half in emails.
  3. GRADE AGAINST THE ANSWER KEY — extraction is scored field-by-field.
  v2 adds a fourth, orthogonal axis: touch CHANNEL is a funnel-stage proxy, so the
  MIX of channels + recency + reciprocity reveals how far a deal has progressed —
  independent of how healthy it is. That's the two dials that are allowed to disagree.

OUTPUTS
-------
  fixtures/envelopes.json      -> raw conversations the app ingests (extraction input)
  fixtures/ground_truth.json   -> the hidden answer key (eval only, not in main UI)
  fixtures/touches.json        -> Outreach/Marketo/call/email activity events feeding
                                  the PROGRESSION score (NOT run through extraction)
"""

import json
import random
import uuid
from datetime import datetime, timedelta
from faker import Faker

# --------------------------------------------------------------------------- #
# 0. Reproducibility
# --------------------------------------------------------------------------- #
SEED = 20260716
fake = Faker()
Faker.seed(SEED)
random.seed(SEED)

TODAY = datetime(2026, 7, 16)
WINDOW_WEEKS = 6

MEDDPICC_FIELDS = [
    "metrics", "economic_buyer", "decision_criteria", "decision_process",
    "paper_process", "identify_pain", "champion", "competition",
]
FRONT_HALF = ["identify_pain", "metrics", "champion", "competition"]
BACK_HALF = ["economic_buyer", "decision_process", "paper_process", "decision_criteria"]
COMPETITORS = ["Zendesk", "ServiceNow", "Zoho", "HubSpot", "Intercom", "an internal build"]

FILLER_ACCOUNTS = [
    "Umbrella Logistics", "Hooli", "Vandelay Industries", "Wayne Enterprises",
    "Wonka Foods", "Cyberdyne Systems", "Soylent Corp", "Pied Piper",
    "Massive Dynamic", "Gekko & Co", "Prestige Worldwide", "Bluth Company",
]
STAGES = ["Discovery", "Evaluation", "Proposal", "Negotiation", "Commit"]

PAINS = [
    "our support tickets are scattered across three different tools and nothing talks to each other",
    "agents waste the first two minutes of every call just figuring out who they're talking to",
    "we have no real visibility into first-response time by team",
    "our current system falls over every time we run a seasonal promotion",
    "reporting is a nightmare - I'm exporting to spreadsheets every single week",
]
METRIC_OUTCOMES = [
    ("cut average handle time by even 20 percent", "around 1.4 million dollars a year in agent capacity"),
    ("get first-response time under an hour", "close to 800 thousand a year in retained accounts"),
    ("deflect a third of tickets to self-service", "about 2 million annually in headcount we wouldn't have to add"),
    ("consolidate onto one platform", "roughly 600 thousand a year in tool spend"),
]
CRITERIA = ["native integrations", "scalability during peak season", "SOC 2 and data residency",
            "ease of admin", "total cost of ownership", "reporting depth"]
SLACK_NOISE = [
    "anyone have the updated pricing one-pager?",
    "great job on the QBR everyone",
    "reminder: forecast calls locked by EOD Friday",
    "who's covering the SE for the demo tomorrow?",
    "coffee chat notes are in the drive",
    "lol the parking at the office event was chaos",
    "can someone approve my expense report",
]

REPS = [fake.name() for _ in range(6)]


def contact(account):
    title = random.choice([
        "VP of Support", "Director of Customer Experience", "Head of CX Ops",
        "Support Operations Manager", "VP of Customer Success",
    ])
    return f"{fake.name()}", title


PLANTED_ACCOUNTS = [
    {
        "account": "Northwind Systems", "stage": "Commit",
        "meddpicc_present": ["identify_pain", "metrics", "champion", "competition", "decision_criteria"],
        "competitor": "Zendesk", "trajectory": "rotting", "has_win_play": False,
        "n_calls": 3, "n_emails": 2, "n_slack": 1,
    },
    {
        "account": "Globex", "stage": "Evaluation",
        "meddpicc_present": ["identify_pain", "metrics", "champion", "competition", "economic_buyer", "decision_process"],
        "competitor": "Zendesk", "trajectory": "healthy", "has_win_play": False,
        "n_calls": 2, "n_emails": 1, "n_slack": 1,
    },
    {
        "account": "Initech", "stage": "Proposal",
        "meddpicc_present": ["identify_pain", "champion", "competition"],
        "competitor": "Zendesk", "trajectory": "healthy", "has_win_play": False,
        "n_calls": 2, "n_emails": 1, "n_slack": 0,
    },
    {
        "account": "Stark Industries", "stage": "Commit",
        "meddpicc_present": ["identify_pain", "metrics", "champion", "competition",
                             "economic_buyer", "decision_process", "paper_process", "decision_criteria"],
        "competitor": "Zendesk", "trajectory": "accelerating", "has_win_play": True,
        "n_calls": 2, "n_emails": 1, "n_slack": 1,
    },
]


def random_ground_truth(account):
    # 'early' = shallow funnel depth, anchors the LOW end of the progression dial.
    trajectory = random.choice(["healthy", "healthy", "rotting", "accelerating", "early"])
    present = [f for f in FRONT_HALF if random.random() < 0.75]
    present += [f for f in BACK_HALF if random.random() < 0.45]
    competitor = random.choice(COMPETITORS) if "competition" in present or random.random() < 0.4 else None
    if competitor and "competition" not in present:
        present.append("competition")
    return {
        "account": account,
        # Fillers never draw 'Commit' — that dramatic stage is reserved for the
        # planted divergence hero (Northwind).
        "stage": random.choice(STAGES[:-1]),
        "meddpicc_present": present,
        "competitor": competitor,
        "trajectory": trajectory,
        "has_win_play": trajectory == "accelerating" and random.random() < 0.5,
        "n_calls": random.randint(1, 3),
        "n_emails": random.randint(0, 2),
        "n_slack": random.randint(0, 1),
    }


def _ts(days_ago, hour=10):
    return (TODAY - timedelta(days=days_ago)).replace(hour=hour, minute=random.randint(0, 59)).isoformat()


def build_call(gt, rep, buyer_name, buyer_title, call_index, pain, metric, escalate_competitor=False):
    acct = gt["account"]
    lines = [f"[00:00] {rep} (Rep): Thanks for making time again. How are things on your end since we last spoke?"]
    if gt["trajectory"] == "rotting" and call_index >= 1:
        lines.append(f"[00:14] {buyer_name} ({buyer_title}, {acct}): Honestly a bit slammed. I'll be straight with you, things have gotten quieter internally on this.")
    elif gt["trajectory"] == "accelerating":
        lines.append(f"[00:12] {buyer_name} ({buyer_title}, {acct}): Good - actually a lot of momentum this week, the team is excited about this.")
    else:
        lines.append(f"[00:11] {buyer_name} ({buyer_title}, {acct}): Busy, but good. Happy to dig in.")
    if "identify_pain" in gt["meddpicc_present"]:
        lines.append(f"[01:20] {buyer_name}: The core issue hasn't changed - {pain}. It's the thing keeping me up at night.")
    if "metrics" in gt["meddpicc_present"]:
        outcome, dollars = metric
        lines.append(f"[03:05] {buyer_name}: If we could {outcome}, my CFO's model puts that at {dollars}. That's the number I'd be measured on.")
    if "competition" in gt["meddpicc_present"] and gt["competitor"]:
        comp = gt["competitor"]
        if escalate_competitor:
            lines.append(f"[05:40] {buyer_name}: I'll be honest, {comp} has been pushing hard. A few folks on my team are leaning their way, so we're taking a serious look at {comp}.")
        else:
            lines.append(f"[05:33] {buyer_name}: We are also evaluating {comp}, just so you know the landscape.")
    if "champion" in gt["meddpicc_present"]:
        if gt["trajectory"] == "rotting" and call_index >= 1:
            lines.append(f"[07:10] {rep} (Rep): Internal note - {buyer_name} has been our champion but is noticeably less responsive this call; may be losing air cover.")
        else:
            lines.append(f"[07:02] {rep} (Rep): Internal note - {buyer_name} is clearly our champion here, actively selling this internally on our behalf.")
    lines.append(f"[09:30] {rep} (Rep): Great, I'll follow up with next steps over email. Appreciate the time.")
    return "\n".join(lines)


def build_email(gt, rep, buyer_name, buyer_title, quiet=False):
    acct = gt["account"]
    body = [f"Subject: RE: {acct} <> next steps", "", f"From: {rep}",
            f"To: {buyer_name} ({buyer_title}, {acct})", "", f"Hi {buyer_name.split()[0]},", "",
            "Following up on our call - a few questions so I can line up the right next steps.", ""]
    if "decision_criteria" in gt["meddpicc_present"]:
        c = random.sample(CRITERIA, 3)
        body.append(f"1. On requirements, you'd mentioned {c[0]}, {c[1]}, and {c[2]} as the things that matter most. Still accurate?")
    body += ["", "Best,", rep, "", "---", "", f"From: {buyer_name}", f"To: {rep}", ""]
    if quiet:
        body.append(f"Hi {rep.split()[0]}, thanks - swamped this week, will circle back. {buyer_name.split()[0]}")
        return "\n".join(body)
    body += [f"Hi {rep.split()[0]},", ""]
    if "economic_buyer" in gt["meddpicc_present"]:
        eb_name = fake.name()
        body.append(f"On sign-off: ultimately this needs {eb_name}, our CFO, to approve the spend - she holds the budget for anything over 100k, so I'll need to bring her in.")
    if "decision_process" in gt["meddpicc_present"]:
        body.append("Process-wise: my team runs the eval, then it goes to a security review, then finance for final approval.")
    if "paper_process" in gt["meddpicc_present"]:
        body.append("Heads up that procurement requires a full legal review and our MSA redlines usually take about three weeks, so we should start that early.")
    if "decision_criteria" in gt["meddpicc_present"]:
        c = random.sample(CRITERIA, 2)
        body.append(f"And yes on requirements - {c[0]} and {c[1]} are the deciders.")
    body += ["", f"Thanks, {buyer_name.split()[0]}"]
    return "\n".join(body)


def build_slack(gt, rep, channel):
    acct = gt["account"]
    others = [r for r in REPS if r != rep] or REPS
    lines = []
    if gt["has_win_play"] and channel == "win-wire":
        comp = gt["competitor"] or "the incumbent"
        lines.append(f"{rep}: closed {acct}! \U0001f389")
        lines.append(f"{rep}: what got us over the line vs {comp} was leaning hard into the migration story - we mapped out a zero-downtime cutover and that's what flipped their ops lead. reusing that on every {comp} deal from now on.")
        lines.append(f"{random.choice(others)}: huge, congrats - stealing that migration angle")
    else:
        comp = gt["competitor"] or random.choice(COMPETITORS)
        lines.append(f"{rep}: anyone hit the '{comp} is cheaper' pushback on {acct}? losing ground on price there")
        lines.append(f"{random.choice(others)}: yeah constant lately, {comp} is discounting aggressively this quarter")
    for note in random.sample(SLACK_NOISE, random.randint(2, 4)):
        lines.append(f"{random.choice(others)}: {note}")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Touch events — structured activity feeding PROGRESSION (never extracted).
#   marketo -> marketing/earliest ; outreach -> BDR/first ; email -> AE mid/late ;
#   gong_call -> AE latest/deepest. The MIX is a funnel-stage proxy; `direction`
#   (inbound == buyer replied) encodes reciprocity. Progression rewards reaching
#   later-stage channels + recent two-way touches — NOT raw volume.
# --------------------------------------------------------------------------- #
FUNNEL_ORDER = ["marketo", "outreach", "email", "gong_call"]
TOUCH_SUMMARIES = {
    "marketo": {"inbound": ["opened nurture email", "downloaded the ROI whitepaper", "clicked webinar invite", "hit the pricing page"],
                "outbound": ["sent nurture email", "added to webinar invite list", "enrolled in drip campaign"]},
    "outreach": {"inbound": ["replied to sequence step 2", "booked intro from cold email", "opened outreach email"],
                 "outbound": ["sent sequence step 1", "no reply to sequence step 1", "sent follow-up, no response"]},
    "email": {"inbound": ["replied to AE follow-up", "shared requirements over email", "looped in a colleague"],
              "outbound": ["sent AE follow-up", "emailed recap, no reply", "chased for next steps"]},
    "gong_call": {"inbound": ["discovery call held", "technical deep-dive call", "exec alignment call"],
                  "outbound": ["pricing call", "left voicemail, call not held", "proposed call time"]},
}


def build_touches(gt, account_id, opp_id):
    traj = gt["trajectory"]
    touches = []
    if traj in ("accelerating", "rotting"):
        max_depth = 3
    elif traj == "healthy":
        max_depth = random.choice([2, 3])
    else:
        max_depth = random.choice([0, 1, 2])
    reached = FUNNEL_ORDER[: max_depth + 1]
    for depth, channel in enumerate(reached):
        n = random.randint(2, 4) if channel in ("marketo", "outreach") else random.randint(1, 3)
        base_day = WINDOW_WEEKS * 7 - int((depth / max(len(reached), 1)) * (WINDOW_WEEKS * 7 - 4))
        for _ in range(n):
            day = max(1, base_day - random.randint(0, 9))
            if traj == "rotting":
                direction = "outbound" if day <= 14 else random.choice(["inbound", "outbound"])
            elif traj == "accelerating":
                direction = "inbound" if random.random() < 0.6 else "outbound"
            elif traj == "healthy":
                direction = "inbound" if random.random() < 0.45 else "outbound"
            else:
                direction = "inbound" if random.random() < 0.25 else "outbound"
            touches.append({
                "touch_id": "tch_" + uuid.UUID(int=random.getrandbits(128)).hex[:10],
                "account_id": account_id, "opp_id": opp_id, "channel": channel,
                "direction": direction, "timestamp": _ts(day),
                "summary": random.choice(TOUCH_SUMMARIES[channel][direction]),
            })
    touches.sort(key=lambda t: t["timestamp"])
    if touches:
        if traj == "accelerating":
            touches[-1]["direction"] = "inbound"
            touches[-1]["summary"] = random.choice(TOUCH_SUMMARIES[touches[-1]["channel"]]["inbound"])
        elif traj == "rotting":
            for t in touches:
                if (TODAY - datetime.fromisoformat(t["timestamp"])).days <= 14 and t["direction"] != "outbound":
                    t["direction"] = "outbound"
                    t["summary"] = random.choice(TOUCH_SUMMARIES[t["channel"]]["outbound"])
    return touches


def envelopes_for_account(gt):
    acct = gt["account"]
    account_id = "acc_" + acct.lower().split()[0]
    opp_id = "opp_" + uuid.UUID(int=random.getrandbits(128)).hex[:8]
    rep = random.choice(REPS)
    buyer_name, buyer_title = contact(acct)
    account_pain = random.choice(PAINS)
    account_metric = random.choice(METRIC_OUTCOMES)
    out = []
    touches = build_touches(gt, account_id, opp_id)
    day_slots = sorted(random.sample(range(3, WINDOW_WEEKS * 7),
                                     gt["n_calls"] + gt["n_emails"] + gt["n_slack"]), reverse=True)
    slot = iter(day_slots)
    for i in range(gt["n_calls"]):
        escalate = gt["trajectory"] == "rotting" and i >= 1
        raw = build_call(gt, rep, buyer_name, buyer_title, i, account_pain, account_metric, escalate_competitor=escalate)
        d = next(slot)
        out.append({"envelope_id": "env_" + uuid.UUID(int=random.getrandbits(128)).hex[:10], "source": "gong_call",
                    "account_id": account_id, "account_name": acct, "opp_id": opp_id, "timestamp": _ts(d), "raw_text": raw,
                    "participants": [rep, f"{buyer_name} ({buyer_title})"],
                    "metadata": {"call_duration_min": random.randint(11, 34), "call_index": i}})
    for j in range(gt["n_emails"]):
        quiet = gt["trajectory"] == "rotting" and j == gt["n_emails"] - 1
        raw = build_email(gt, rep, buyer_name, buyer_title, quiet=quiet)
        d = next(slot)
        out.append({"envelope_id": "env_" + uuid.UUID(int=random.getrandbits(128)).hex[:10], "source": "gong_email",
                    "account_id": account_id, "account_name": acct, "opp_id": opp_id, "timestamp": _ts(d), "raw_text": raw,
                    "participants": [rep, f"{buyer_name} ({buyer_title})"],
                    "metadata": {"subject": f"RE: {acct} <> next steps", "quiet_reply": quiet}})
    for k in range(gt["n_slack"]):
        channel = "win-wire" if gt["has_win_play"] else "deal-help"
        raw = build_slack(gt, rep, channel)
        d = next(slot)
        out.append({"envelope_id": "env_" + uuid.UUID(int=random.getrandbits(128)).hex[:10], "source": "slack",
                    "account_id": account_id, "account_name": acct, "opp_id": opp_id, "timestamp": _ts(d), "raw_text": raw,
                    "participants": [rep], "metadata": {"channel": f"#{channel}"}})
    return out, touches, {
        "account": acct, "account_id": account_id, "opp_id": opp_id, "crm_stage": gt["stage"],
        "meddpicc_present": sorted(set(gt["meddpicc_present"])),
        "meddpicc_absent": sorted(set(MEDDPICC_FIELDS) - set(gt["meddpicc_present"])),
        "competitor": gt["competitor"], "trajectory": gt["trajectory"], "has_win_play": gt["has_win_play"],
    }


def main():
    ground_truths = list(PLANTED_ACCOUNTS)
    planted_names = {gt["account"] for gt in PLANTED_ACCOUNTS}
    fillers = [a for a in FILLER_ACCOUNTS if a not in planted_names]
    for acct in fillers[: 12 - len(PLANTED_ACCOUNTS)]:
        ground_truths.append(random_ground_truth(acct))
    assert len({gt["account"] for gt in ground_truths}) == len(ground_truths), "duplicate account name"
    all_envelopes, all_touches, answer_key = [], [], []
    for gt in ground_truths:
        envs, touches, key = envelopes_for_account(gt)
        all_envelopes.extend(envs)
        all_touches.extend(touches)
        answer_key.append(key)
    all_envelopes.sort(key=lambda e: e["timestamp"])
    all_touches.sort(key=lambda t: t["timestamp"])
    import os
    os.makedirs("fixtures", exist_ok=True)
    with open("fixtures/envelopes.json", "w") as f:
        json.dump(all_envelopes, f, indent=2)
    with open("fixtures/ground_truth.json", "w") as f:
        json.dump(answer_key, f, indent=2)
    with open("fixtures/touches.json", "w") as f:
        json.dump(all_touches, f, indent=2)
    print(f"Accounts: {len(answer_key)}  Envelopes: {len(all_envelopes)}  Touches: {len(all_touches)}")


if __name__ == "__main__":
    main()
